# Site settings
title: LOOKING FOR PEACE
email: lsanotes@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Peace in life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lsanotes.github.io" # the base hostname & protocol for your site
twitter_username: lsanotes
github_username:  lsanotes

# Build settings
markdown: kramdown
